kind: project
metadata:
  name: mobility-data
  created: '2024-05-28T06:33:21.230000'
spec:
  functions:
  - url: src/download-data.py
    name: download-dem
    kind: job
    handler: download_dem
    requirements:
    - rasterio
    - xarray
    - rioxarray
    - owslib
    - osmnx
    - h3
    - folium
    - pandas==1.3.5
  - url: src/download-data.py
    name: download-osm
    kind: job
    handler: download_osm
    requirements:
    - rasterio
    - xarray
    - rioxarray
    - owslib
    - osmnx
    - h3
    - folium
    - pandas==1.3.5
  - url: src/download-data.py
    name: merge-osm-dem
    kind: job
    handler: merge_osm_dem
    requirements:
    - rasterio
    - xarray
    - rioxarray
    - owslib
    - osmnx
    - h3
    - folium
    - pandas==1.3.5
  - url: src/download-open-data.py
    name: download-road-areas
    kind: job
    handler: download_road_areas
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-road-edges
    kind: job
    handler: download_road_edges
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-road-nodes
    kind: job
    handler: download_road_nodes
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-curves
    kind: job
    handler: download_curves
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-sidewalks
    kind: job
    handler: download_sidewalks
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-city30
    kind: job
    handler: download_city_30
    requirements:
    - geopandas==0.13.2
  - url: src/download-spire.py
    name: download-traffic-spire
    kind: job
    handler: get_spire
  - url: src/download-open-data.py
    name: download-charging-stations
    kind: job
    handler: download_charging_stations
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-bike-path
    kind: job
    handler: download_bike_path
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-incidents
    kind: job
    handler: download_incidents
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-bike-parking-places
    kind: job
    handler: download_bike_parking_places
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-car-parkings
    kind: job
    handler: download_car_parkings
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-bus-stops-tper
    kind: job
    handler: download_bus_stops_tper
    requirements:
    - geopandas==0.13.2
  - url: src/download-open-data.py
    name: download-train-stops-tper
    kind: job
    handler: download_train_stops_tper
    requirements:
    - geopandas==0.13.2
  - url: src/download-spire.py
    name: download-traffic-spire-accuracy
    kind: job
    handler: get_spire_accur
  workflows:
  - path: ./src/mobility-data-pipeline.py
    name: mobility-data-pipeline
    handler: pipeline
  artifacts: []
  conda: ''
  source: git://github.com/Gemello-Digitale-Bologna/datacollector-mobility.git#refs/heads/master
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
